name: ${project.name}
main: ${main.class}
version: ${project.version}
author: kluberge
description: Allows one to instantly fell trees
commands:
  treefellerplus:
    description: Reload TreeFellerPlus
    aliases: [treefeller, tf, tfp]
    permission: treefellerplus.reload
    usage: /treefellerplus reload
permissions:
  treefellerplus.use:
    description: Allows player to cut down entire trees
      default: true
  treefellerplus.reload:
      description: Allows player to reload plugin
      default: op
